# Generated by Django 4.2.2 on 2024-08-06 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiorecording',
            name='uniq_id',
            field=models.CharField(blank=True, max_length=5, null=True, unique=True),
        ),
    ]
