# Generated by Django 4.2.2 on 2024-08-06 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adom', '0002_audiorecording_uniq_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiorecording',
            name='audio_data',
            field=models.FileField(blank=True, null=True, upload_to='audio_recordings/'),
        ),
    ]
