# Generated by Django 4.2.2 on 2024-08-06 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adom', '0003_alter_audiorecording_audio_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiorecording',
            name='audio_data',
            field=models.TextField(),
        ),
    ]
