# Generated by Django 4.1.5 on 2024-08-08 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adom', '0005_audiorecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiorecord',
            name='file_path',
        ),
    ]
