# Generated by Django 4.2.2 on 2024-08-10 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adom', '0006_remove_audiorecord_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiorecord',
            name='tempo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='audiorecord',
            name='upload_datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='AudioRecordo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_datetime', models.DateTimeField()),
                ('hymn_number', models.CharField(max_length=10)),
                ('random_letters', models.CharField(max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
