# Generated by Django 4.2.2 on 2023-07-01 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mazing', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Students',
            new_name='Participant',
        ),
    ]
