# Generated by Django 4.2.2 on 2023-07-01 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mazing', '0002_rename_students_participant'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='uniqueid',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
